// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://kxmkmztjrpntusibvaor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4bWttenRqcnBudHVzaWJ2YW9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg3NzkyNzAsImV4cCI6MjA5NDM1NTI3MH0.nVVBkPXo2aRI9oB9gL7YM3giNy-qP3SGy9Dn-JDgWf4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
auth: {
  storage: localStorage,
  persistSession: true,
  autoRefreshToken: true,
}
});